### ISSUE TITLE
Meta bindings are undefined

### ISSUE THREAD

**Issue by TheGitMux** [ErnestKz/KeyWork#3]
Hello,
     When `KW-insert` mode is called, binding such as `M-b` (backward-word) and `M-f` (forward-word) become undefined. The control bindings, such as `C-a` (move-beginning-of-line) remain bound. How do I make `Meta` bindings persist to `KW-insert`?

```
(load-file "~/Internet/Git/Emacs/Modal/KeyWork/monad.el/monad.el")
(load-file "~/Internet/Git/Emacs/Modal/KeyWork/ParserMonad.el/ParserMonad.el")
(load-file "~/Internet/Git/Emacs/Modal/KeyWork/KeyWork.el")

(KeyWork
 KW-insert
 "#ff0000" hollow
  ("ESC"         !KW-command))

(KeyWork
 KW-command
 "#ff0000" box
 ("j"           backward-char)
 ("k"           next-line)
 ("l"           previous-line)
 (";"           forward-char)
 ("i"           !KW-insert))

(KeyWork-mode t)
(KeyWork-on 'KW-insert)

(add-hook 'minibuffer-setup-hook (lambda () (KeyWork-on 'KW-insert)))
(add-hook 'minibuffer-exit-hook (lambda () (KeyWork-on 'KW-command)))
```

**Comment by ErnestKz** [comment]
That's very unexpected behaviour. I did some testing and it turns out that ESC is a special key which emacs invokes under the hood whenever doing M-<whatever>. https://www.gnu.org/software/emacs/manual/html_node/elisp/Functions-for-Key-Lookup.html#index-meta_002dprefix_002dchar
So when you do M-f, (or any other M- keychord), emacs tries to do ESC f, but ESC is rebound in kw-insert mode, so it doesnt succeed.

So you could either pick a different key apart from ESC, or, you can set `meta-prefix-key` to some other key thats not ESC and then rebind all the keysequences of ESC-.... to that new key you've chosen. The latter option might get very messy unless you know a clean way to do it.

**Comment by TheGitMux** [comment]
I will rebind the layer toggle from `ESC`.

Thank you,
Git Mux
